[project]
name = "llm-system"
version = "0.1.0"
requires-python = ">=3.10,<3.13"
dependencies = [
    "accelerate>=1.12.0",
    "pydantic>=2.12.5",
    "requests>=2.32.5",
    "sentencepiece>=0.2.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "wandb>=0.23.1",
]
